### ISSUE TITLE
RDTIME CSR decode error for RV32I

### ISSUE THREAD

**Issue by kpgriesser** [tactcomplabs/rev#326]
**Describe the bug**
The RDTIME CSR is accessing in 64-bit mode but REV throws a decode error for 32-bit mode. 

**To Reproduce**
In latest REV:
```
git checkout fast-print-test
cd rev/test/tracer
bug-rdtime.sh
```
This will first compile and run for 64-bit mode and print out 'Time check: 268'
Then it will compile and run 32-bit mode which results in :
`FATAL: RevCPU[cpu0:DecodeInst:27795000]: Error: failed to decode instruction at PC=0x11d60; Enc=627`

To confirm the decode error is on the CSR access:
```
$ grep -i 11d60 bug-rdtime.rv32i.dis 
   11d60:	c01027f3          	rdtime	a5
```

**Comment by kpgriesser** [comment]
Upon further reading I see
`For base ISAs with XLEN=32, the Zicntr extension enables the three 64-bit read-only counters to be accessed in 32-bit pieces. The RDCYCLE, RDTIME, and RDINSTRET pseudoinstructions provide the lower 32 bits, and the RDCYCLEH, RDTIMEH, and RDINSTRETH pseudoinstructions provide the upper 32 bits of the respective counters.`

So, I'll test that and close this

**Comment by kpgriesser** [comment]
verified using rv32g machine.
closing - pilot error

**Comment by leekillough** [comment]
The same opcodes / CSRs for RV64 should be decoded properly as the lower half of the CSR register in RV32 mode. It should not be throwing a decode error in RV32 when the same instruction works on RV64.

If you access `rdtimeh`, `rdcycleh` or `rdinstreth` in RV64, those are invalid instructions on RV64.

**Comment by leekillough** [comment]
See the logic in `Zicsr.h` and `RevRegFile.h` for how perf counter CSRs are handled.

You may want to reopen this if `rdcycle`, `rdtime`, and `rdinstret` are working in RV64 but not RV32. They should work unchanged and return the lower half on RV32 and the whole 64-bit value on RV64.

**Comment by leekillough** [comment]
See the tests I already wrote in `test/` for these perf counters.

**Comment by kpgriesser** [comment]
Taking a 2nd look. I don't know if this is correct but it is a little confusing:
For REV CPU:
- The RDTIME/RDTIMEH and friends only live in Zicsr.h so REV will not decode them for RV_I cases. So I'm now using RV_G for both 32 and 64 bit. This makes sense.

For the compiler:
- When I compile with -march=rv32i,  the RDTIME instructions are honored and put in the code. This seems inconsistent.
- When adding RDTIMEH into the code, it does not compile using -march=rv64g ( as expected )

I think REV is fine... the compiler, however, not so sure but probably OK

**Comment by leekillough** [comment]
> Taking a 2nd look. I don't know if this is correct but it is a little confusing: For REV CPU:
> 
>     * The RDTIME/RDTIMEH and friends only live in Zicsr.h so REV will not decode them for RV_I cases. So I'm now using RV_G for both 32 and 64 bit. This makes sense.

I cannot find that comment in the Rev source tree. It was not a comment I made.

`RV_G` implies `D` implies `F`  implies `Zicsr`. So this is probably someone saying that they're taking the easier route of only testing the performance counters on `RV_G` and not on `RV_I` + `Zicsr` or `RV_I` + `Zicnt`.
 
> For the compiler:
> 
>     * When I compile with -march=rv32i,  the RDTIME instructions are honored and put in the code. This seems inconsistent.

If `F` is enabled or implied, then `Zicsr` is implied.

I noticed that the performance counters were separated into their own `Zicnt`, but I did not separate it out as a superset of `Zicsr` -- I simply enabled `Zicnt` features whenever `Zicsr` was enabled, since `Zicnt` does not add new instructions not in `Zicsr` (which `Zicnt` implies), but only enables accessing the CSR registers corresponding to `RDTIME`, `RDCYCLE`, `RDINSTRET`, (and `RDTIMEH`, `RDCYCLEH`, and `RDINSTRETH` on RV32). But I guess you can have `Zicsr` without `Zicnt`, so to be pure about it we'd have to handle `Zicnt` registers separately and throw errors if `Zicnt` isn't enabled even though the vast majority of the code is the same in `Zicsr` and it's only when you are reading or writing a specific CSR register that we have to check whether it's enabled and throw an error if it's not.

>     * When adding RDTIMEH into the code, it does not compile using -march=rv64g ( as expected )

It could still compile as inline assembly, but give an illegal instruction when executed (Rev does not yet implement traps, so it just calls SST's `fatal()` when something like this happens). Performance counter instructions are  _pseudoinstructions_ accessing specific CSR registers, but otherwise their format is the same as all other CSR access/modify instructions.

That is why I split the CSR implementation into `Zicsr.h` and `RevRegFile.h`. `Zicsr.h` which is implied by `F` (and thus `D` and `G` too), simply enables the CSR instructions and the logic that they perform, such as purely writing, reading and setting bits, and reading and clearing bits. These instructions' encoding and their logic are the same for all CSR instructions, and the CSR register number is one of their immediate operands. `GetCSR()` and `SetCSR` are in `RevRegFile.h`, analogous to `GetX` and `SetX`. That is where the semantics of a specific CSR register are handled, like reading the `RDTIME` counter.

CSR registers are special registers, and there are only 6 instructions in the total RISC-V ISA to access / modify them. `RDTIME` and the like are _pseudo-instructions_ with a specific CSR register and a specific access or modify operation. We program the semantics of getting and setting specific CSR registers in `RevRegFile.h`; we program the decoding and generalized execution of 6 CSR instructions in `Zicsr.h`, which is only called if the `Zicsr` extension has been enabled, directly or indirectly.

> I think REV is fine... the compiler, however, not so sure but probably OK

The compiler should accept all CSR instructions and pseudo-instructions, possibly even if `Zicsr` hasn't been enabled in the `-march=` string. But when the code is executed, the simulators should fault on such instructions if `Zicsr` isn't enabled. The CSR space has been mapped out (see the Privileged spec and my listing in `RevRegFile.h`), and whether a specific CSR register has been enabled or not is very specific to that CSR register, and is not something that the hardware (or Rev's software) should concern itself with during _decoding_. Accepting and encoding, and Rev accepting and decoding, CSR instructions, are orthogonal to whether a specific CSR register has been enabled. And the CSR register being operated on, such as `RDTIME`, is an operand to one of the six instructions which operate the same on all CSR registers -- it's not considered a separate instruction which should be accepted or rejected at encoding/decoding time.

**Comment by leekillough** [comment]
That `rdtime` etc. are in the table of `Zicsr.h` is simply a way of printing their canonical names when their CSR register and CSR operation appears in a CSR instruction. The code paths and conditions for decoding instructions are the same for `RDTIME` etc. as all other CSR instructions -- it's just that we print `rdtime` like `objdump -d` does when the CSR register is the TIME register ( 0xc01 ) and the operation is a CSR register read while not setting any bits. When that canonical form is seen, we print it out as `rdtime rd` instead of `csrrs 0xc01, zero, rd`. Otherwise all other paths in `Zicsr.h` and in instruction decoding is the same as all other CSR instructions/registers, and it's only when `RevRegFile::GetCSR( 0xc01 )` is called, that the TIME register is handled specially.
